version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: database
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: test
    restart: always
    entrypoint: ["mkdir", "data/migrations"]
    volumes:
      - mongodata:/data/db
      - migrations:/data/migrations
  
  # backend:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - 4000:4000
  
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - 3000:3000


volumes:
  mongodata:
    driver: local
  migrations:
    driver: local
    driver_opts:
      type: none
      device: /src/migrations